export const AUTO_TOPUP_CONSTANTS = {
  MIN_THRESHOLD_CREDITS: 150,
  DEFAULT_THRESHOLD_CREDITS: 500,
  MAX_THRESHOLD_CREDITS: 5000,
  MIN_TOPUP_DOLLARS: 10.0,
  DEFAULT_TOPUP_DOLLARS: 20.0,
  MAX_TOPUP_DOLLARS: 100.0,
  CENTS_PER_CREDIT: 1,
} as const
